TOKEN = '920710380:AAG8uT7mRjpMXDkY13v4OZyrxt2jMV0JE6Y'
CHAT = 'None'
start_mess = 'Привет! \n\nПиши сюда свои вопросы, и мы ответим на них!'
help_mess = 'Это бот помошник'
success_mess = 'Мы получили твоё сообщение!'
